//! Generated CTSC golden-matrix loading and structural invariant checks.
//!
//! Helpers resolve repository-relative artifacts without changing golden bytes;
//! `check_shape` rejects duplicate rows and incomplete language/variant coverage.

#![cfg(any(test, feature = "test-util"))]

// Cohesive implementation group for this subsystem.
use super::*;

/// Locate the repository root containing the checked-in matrix.
pub(super) fn repo_root(start: impl AsRef<Path>) -> PathBuf {
    start
        .as_ref()
        .ancestors()
        .find(|path| path.join("rust").join("Cargo.toml").is_file() && path.join("justfile").is_file())
        .expect("repository root")
        .to_path_buf()
}

/// Resolve a repository-relative path without requiring the caller to join it.
pub(super) fn repo_path(root: impl AsRef<Path>, relative: impl AsRef<Path>) -> PathBuf {
    root.as_ref().join(relative)
}

/// Read exact golden bytes or stop the test with path context.
pub(super) fn read_bytes(path: impl AsRef<Path>) -> Vec<u8> {
    std::fs::read(path.as_ref()).unwrap_or_else(|error| panic!("failed to read {}: {error}", path.as_ref().display()))
}

/// Publish exact generated bytes, creating the containing directory.
pub(super) fn write_bytes(path: impl AsRef<Path>, bytes: impl AsRef<[u8]>) -> Result<(), GoldenError> {
    let path = path.as_ref();
    let parent = path.parent().expect("artifact parent");
    std::fs::create_dir_all(parent).map_err(|error| GoldenError::wrap(format!("failed to create {}", parent.display()), error))?;
    std::fs::write(path, bytes.as_ref()).map_err(|error| GoldenError::wrap(format!("failed to write {}", path.display()), error))
}

/// Decode matrix JSON from any reader.
pub(super) fn parse_matrix(reader: impl std::io::Read) -> Result<Matrix, serde_json::Error> {
    serde_json::from_reader(reader)
}

/// Load the checked-in matrix rooted at the supplied repository.
pub(super) fn load_matrix(root: impl AsRef<Path>) -> Matrix {
    let path = repo_path(root, "test/goldens/ctsc").join(matrix_file());
    let file = std::fs::File::open(&path).unwrap_or_else(|error| panic!("failed to read {}: {error}", path.display()));
    let matrix = parse_matrix(file).unwrap_or_else(|error| panic!("{} is not a valid golden matrix: {error}", path.display()));
    assert_eq!(matrix.format, MATRIX_FORMAT, "unexpected matrix format");
    assert_eq!(matrix.format_version, MATRIX_VERSION, "unexpected matrix format version");
    assert_eq!(
        matrix.artifact_root.as_str(),
        "test/goldens/ctsc",
        "unexpected matrix artifact root"
    );
    matrix
}
// ---------------------------------------------------------------------------
// Matrix shape, source coverage, and replacement references
// ---------------------------------------------------------------------------

/// Enforce unique rows and complete required language/variant coverage.
pub(super) fn check_shape(matrix: &Matrix) {
    let mut ids = HashSet::with_capacity(matrix.rows.len());
    let mut components = BTreeSet::new();
    for row in &matrix.rows {
        assert!(ids.insert(row.id.clone()), "duplicate matrix row id '{}'", row.id);
        assert!(
            !row.id.starts_with('/') && !row.id.ends_with('/') && !row.id.contains("..") && !row.id.contains('\\'),
            "matrix row id '{}' must be a relative forward-slash artifact path",
            row.id
        );
        assert!(!row.source_group.is_empty(), "row '{}' must declare a source group", row.id);
        assert_eq!(
            row.captures_rust(),
            row.replay.mode != ReplayMode::NotApplicable,
            "row '{}' must declare a replay mode exactly when it captures a Rust bundle",
            row.id
        );
        if row.parity.mode != ParityMode::ByteIdentical {
            assert!(
                row.parity.reason.as_ref().is_some_and(|reason| !reason.is_empty()),
                "row '{}' parity mode '{:?}' requires an explicit reason",
                row.id,
                row.parity.mode
            );
        }
        if row.parity.mode == ParityMode::Exception {
            assert!(
                !row.parity.allowed_differences.is_empty(),
                "row '{}' is a parity exception and must declare the exact differences it allows",
                row.id
            );
            let mut declared = BTreeSet::new();
            for difference in &row.parity.allowed_differences {
                assert!(
                    difference.path.starts_with('/'),
                    "row '{}' declares parity difference path '{}', which is not a JSON Pointer",
                    row.id,
                    difference.path
                );
                assert!(
                    difference.rust != difference.csharp,
                    "row '{}' declares an identical parity difference at '{}'",
                    row.id,
                    difference.path
                );
                assert!(
                    declared.insert(difference.render()),
                    "row '{}' declares the same parity difference twice at '{}'",
                    row.id,
                    difference.path
                );
            }
        } else {
            assert!(
                row.parity.allowed_differences.is_empty(),
                "row '{}' declares parity differences but its mode is '{:?}'",
                row.id,
                row.parity.mode
            );
        }
        if row.replay.mode != ReplayMode::Verified {
            assert!(
                row.replay.reason.as_ref().is_some_and(|reason| !reason.is_empty()),
                "row '{}' replay mode '{:?}' requires an explicit reason",
                row.id,
                row.replay.mode
            );
        }
        if row.replay.mode == ReplayMode::Unsupported {
            let category = row
                .replay
                .expect_category
                .as_deref()
                .unwrap_or_else(|| panic!("row '{}' marks replay unsupported and must declare expectCategory", row.id));
            assert!(
                REPLAY_FAILURES.contains(&category),
                "row '{}' declares unknown replay failure category '{category}'",
                row.id
            );
        } else {
            assert!(
                row.replay.expect_category.is_none(),
                "row '{}' declares replay expectCategory but its mode is '{:?}'",
                row.id,
                row.replay.mode
            );
        }
        assert_eq!(
            row.captures_rust(),
            row.linkage_mode() == LinkageMode::Linked,
            "row '{}' must declare linkage 'linked' exactly when it captures a Rust bundle",
            row.id
        );
        for language in [row.rust.as_ref(), row.csharp.as_ref()].into_iter().flatten() {
            assert!(
                matrix.bindings.contains_key(&language.binding),
                "row '{}' references unknown binding '{}'",
                row.id,
                language.binding
            );
            assert!(!language.phases.is_empty(), "row '{}' must declare at least one phase", row.id);
            if language.expect == Expectation::Failure {
                assert!(
                    language.expect_category.is_some(),
                    "row '{}' expects failure and must declare expectCategory",
                    row.id
                );
            }
        }
        match row.classification {
            Classification::ImplementationComponent => {
                let component = row
                    .component
                    .as_ref()
                    .unwrap_or_else(|| panic!("row '{}' must name a component", row.id));
                assert!(
                    components.insert(component.clone()),
                    "component '{component}' is covered by more than one matrix row"
                );
                assert_eq!(
                    row.id.as_str(),
                    format!("component/{component}"),
                    "component row id must be 'component/<component>'"
                );
                let rust = row
                    .rust
                    .as_ref()
                    .unwrap_or_else(|| panic!("component row '{}' must declare Rust coverage", row.id));
                assert!(!row.sources.is_empty(), "component row '{}' must list its sources", row.id);
                let rust_artifacts = if row.captures_rust() {
                    vec![
                        RepoPath::from_path(manifest_file()).expect("manifest artifact name must be portable"),
                        RepoPath::from_path(trace_file()).expect("trace artifact name must be portable"),
                        RepoPath::from_path(registry_file()).expect("registry artifact name must be portable"),
                    ]
                } else {
                    vec![RepoPath::from_path(registry_file()).expect("registry artifact name must be portable")]
                };
                assert_eq!(
                    rust.artifacts, rust_artifacts,
                    "component row '{}' declares the wrong Rust artifact set",
                    row.id
                );
                if let Some(csharp) = row.csharp.as_ref() {
                    assert_eq!(
                        csharp.artifacts,
                        vec![RepoPath::from_path(registry_file()).expect("registry artifact name must be portable")],
                        "C# coverage is registry-only; row '{}' declares more",
                        row.id
                    );
                    assert_eq!(
                        csharp.phases,
                        vec![Phase::Discover],
                        "C# coverage is discovery-only; row '{}' declares more",
                        row.id
                    );
                }
            }
            Classification::NegativeFixture => {
                assert!(row.id.starts_with("negative/"), "negative row id must start with 'negative/'");
                assert!(!row.sources.is_empty(), "negative row '{}' must list its sources", row.id);
                let language = row
                    .rust
                    .as_ref()
                    .unwrap_or_else(|| panic!("negative row '{}' needs Rust coverage", row.id));
                assert_eq!(
                    language.expect,
                    Expectation::Failure,
                    "negative row '{}' must expect failure",
                    row.id
                );
                assert_eq!(
                    language.artifacts,
                    vec![RepoPath::from_path(error_file()).expect("error artifact name must be portable")],
                    "negative row '{}' must produce exactly {}",
                    row.id,
                    error_file().display()
                );
            }
            Classification::Replacement => {
                assert!(
                    row.id.starts_with("replacement/"),
                    "replacement row id must start with 'replacement/'"
                );
                assert!(
                    row.rust.is_none() && row.csharp.is_none(),
                    "replacement row '{}' owns no artifacts",
                    row.id
                );
                let replacement = row
                    .replacement
                    .as_ref()
                    .unwrap_or_else(|| panic!("replacement row '{}' must describe what it replaces", row.id));
                assert!(!replacement.feature.is_empty(), "replacement row '{}' needs a feature", row.id);
                assert!(!replacement.rationale.is_empty(), "replacement row '{}' needs a rationale", row.id);
                assert!(
                    !replacement.references.is_empty(),
                    "replacement row '{}' must point at CTSC-native tests",
                    row.id
                );
            }
        }
        for limitation in &row.limitations {
            assert!(
                !limitation.code.is_empty() && !limitation.detail.is_empty(),
                "row '{}' declares an empty limitation",
                row.id
            );
            assert!(
                limitation.code != ASYNC_LIMITATION || !row.captures_rust(),
                "row '{}' declares '{ASYNC_LIMITATION}' and must stay discovery-only",
                row.id
            );
        }
        assert!(
            row.capture_exclusions.is_empty() || row.classification == Classification::ImplementationComponent && row.captures_rust(),
            "row '{}' may declare captureExclusions only for a captured component",
            row.id
        );
        let mut excluded_operations = BTreeSet::new();
        for exclusion in &row.capture_exclusions {
            assert!(
                !exclusion.operation.is_empty() && is_stable(&exclusion.code) && !exclusion.reason.is_empty(),
                "row '{}' declares an invalid capture exclusion; operation, stable code, and reason are required",
                row.id
            );
            assert!(
                excluded_operations.insert(exclusion.operation.as_str()),
                "row '{}' excludes capture of operation '{}' more than once",
                row.id,
                exclusion.operation
            );
        }
    }
}
