using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace SpecGate.WitnessGenerator;

/// <summary>
/// A build-time source generator that emits a single <c>[SpecOperation]</c>,
/// used as a conformance witness for the harness's build fidelity: the emitted
/// operation exists only in the real compiled assembly (its source lives in
/// <c>obj/generated</c>), so it is invisible to any source-globbing or
/// source-scanning surrogate but present when the harness builds and reflects
/// over the fixture's real assembly.
/// </summary>
[Generator]
public sealed class WitnessGenerator : IIncrementalGenerator
{
    /// <summary>Registers the fixed generated source.</summary>
    /// <param name="context">The incremental generator initialization context.</param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
            ctx.AddSource("GeneratedWitnessOps.g.cs", SourceText.From(Source, Encoding.UTF8)));
    }

    private const string Source = @"// <auto-generated/>
using SpecGate.Annotations;

namespace SpecGateFixtures.Conformance.Witness;

/// <summary>Operation emitted by a build-time source generator (real-build witness).</summary>
public static class GeneratedWitnessOps
{
    /// <summary>Increments the seed. Exists only in the real compiled assembly.</summary>
    [SpecOperation(""witness"", Spec = ""fixture.realbuild_witness"")]
    public static int Witness([SpecInput(""seed"")] int seed) => seed + 1;
}
";
}
