//! Emits the real-build witness operation into `OUT_DIR` at build time.
//!
//! The generated `witness` operation therefore exists only in the compiled
//! crate — never as a source file on disk — mirroring the C# Roslyn source
//! generator. It is the Rust half of the cross-binding real-build witness: a
//! source-scanning runner cannot see it, so running it proves the harness
//! executes the fixture's real built artifact rather than a source surrogate.
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR not set"));
    let dest = out_dir.join("generated_witness.rs");
    fs::write(&dest, GENERATED_WITNESS).expect("failed to write generated witness op");
    println!("cargo:rerun-if-changed=build.rs");
}

const GENERATED_WITNESS: &str = r#"// @generated by build.rs — real-build witness (no source file on disk).
#[spec_operation("witness", spec = "fixture.realbuild_witness")]
pub fn witness(seed: i32) -> i32 {
    seed + 1
}
"#;
