<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <RootNamespace>SpecGate.Runtime</RootNamespace>
    <AssemblyName>SpecGate.Runtime</AssemblyName>
  </PropertyGroup>
</Project>
