//! Tests for `discovery_registry_handles_methods_and_duplicates`.
//!
//! Verifies spec case:
//!   - Method operations inside `impl` blocks register metadata without compile failures.
//!   - `#[spec_setup]` functions register metadata with `is_setup: true`.
//!   - Reusing the same operation name in different source files does NOT cause
//!     registry symbol collisions (the fixture crate has two `increment` methods
//!     in different modules — `statemachine_counter` and `setup_with_params`).
//!   - `specgate_runtime::discovery_json()` returns valid JSON listing those entries.
//!
//! These imports force the fixture modules into the test binary so their
//! `distributed_slice` statics (generated by `#[spec_operation]` / `#[spec_setup]`)
//! are registered in `SPECGATE_OPS`.

use specgate::__rt::discovery_json;

// Force the relevant fixture modules into this test binary so their
// distributed_slice registration statics are linked in.
use specgate_fixtures::multi_field_capture;
use specgate_fixtures::setup_with_params;
use specgate_fixtures::stateless_add;
use specgate_fixtures::statemachine_counter;

/// `discovery_json()` must return valid JSON (parseable JSON object with
/// an "operations" array).
#[test]
fn discovery_json_is_valid_json() {
    let json = discovery_json();
    assert!(
        json.starts_with('{') && json.ends_with('}'),
        "discovery_json must return a JSON object; got: {json}"
    );
    assert!(
        json.contains("\"operations\":["),
        "discovery_json must have an 'operations' array; got: {json}"
    );
    assert!(
        json.contains("\"types\":["),
        "discovery_json must have a 'types' array; got: {json}"
    );
}

/// Free-function operations must be registered.
#[test]
fn free_function_operation_is_registered() {
    // Trigger module import side-effects.
    let _ = std::panic::catch_unwind(|| {
        let _ = stateless_add::add(0, 0);
    });

    let json = discovery_json();
    assert!(
        json.contains("\"fn_name\":\"add\""),
        "free function operation 'add' must be registered in discovery_json; got: {json}"
    );
}

/// Method operations (with `&mut self` receiver) inside `impl` blocks must be
/// registered — this is the primary regression guard for the impl-block fix.
#[test]
fn method_operation_inside_impl_block_is_registered() {
    // Trigger module import side-effects.
    let _ = std::panic::catch_unwind(|| {
        let mut c = statemachine_counter::make_counter();
        c.increment();
    });

    let json = discovery_json();
    assert!(
        json.contains("\"fn_name\":\"increment\""),
        "method operation 'increment' (impl Counter) must be registered in discovery_json; got: {json}"
    );
    assert!(
        json.contains("\"fn_name\":\"withdraw\""),
        "method operation 'withdraw' (impl Account) must be registered in discovery_json; got: {json}"
    );
}

/// `#[spec_setup]` functions must register metadata with `is_setup: true`.
#[test]
fn spec_setup_registers_with_is_setup_true() {
    // Trigger module import side-effects.
    let _ = statemachine_counter::make_counter();
    let _ = setup_with_params::make_counter(0);

    let json = discovery_json();
    assert!(
        json.contains("\"is_setup\":true"),
        "spec_setup must register metadata with is_setup: true; got: {json}"
    );
    assert!(
        json.contains("\"fn_name\":\"make_counter\""),
        "setup function 'make_counter' must appear in registry; got: {json}"
    );
    // Ensure make_counter is paired with is_setup: true (not just present).
    // The JSON pairs fn_name and is_setup in the same object, so check proximity.
    // Both statemachine_counter and setup_with_params register make_counter as a setup.
    let make_counter_setup_count = count_occurrences(&json, "\"fn_name\":\"make_counter\"");
    assert!(
        make_counter_setup_count >= 2,
        "both modules that define make_counter must register it (no collision dedup); got: {json}"
    );
}

/// Duplicate operation names across different source files must NOT cause
/// symbol collisions. Both `statemachine_counter` and `setup_with_params`
/// define a method named `increment` — both must appear in the registry.
#[test]
fn duplicate_operation_names_across_modules_do_not_collide() {
    // Force both modules to link in.
    let _ = statemachine_counter::make_counter();
    let _ = setup_with_params::make_counter(0);
    let _ = multi_field_capture::make_account();

    let json = discovery_json();

    // Both `increment` entries (from two different modules) must be present.
    let increment_count = count_occurrences(&json, "\"fn_name\":\"increment\"");
    assert!(
        increment_count >= 2,
        "both 'increment' operations (statemachine_counter and setup_with_params) \
         must register without collision; got {increment_count} entries in: {json}"
    );
}

// ---------------------------------------------------------------------------
// Helper
// ---------------------------------------------------------------------------

fn count_occurrences(haystack: &str, needle: &str) -> usize {
    let mut count = 0;
    let mut start = 0;
    while let Some(pos) = haystack[start..].find(needle) {
        count += 1;
        start += pos + needle.len();
    }
    count
}
