//! Mechanism proof tests.
//!
//! DO NOT EDIT THIS FILE. These tests are hand-written constraints that
//! verify the harness compiles and executes real code. They are not generated
//! from a spec and must not be modified by any automated tool or agent.
//! If these tests fail, the annotations crate needs to be fixed — not this file.
//!
//! These tests import COMPILED fixture code and verify that the annotation
//! proc macros produce real trace events at runtime. If the harness were to
//! "interpret" source files instead of compiling and executing them, these
//! tests would fail because:
//!
//! 1. They import from `specgate_fixtures`, forcing it to compile.
//! 2. Compilation forces `specgate_annotations` proc macros to expand.
//! 3. The expanded code must emit trace events at runtime.
//! 4. We retrieve traces and assert they are non-empty.
//!
//! A no-op annotation crate produces empty traces → test failure.
//! An interpreter bypass never reaches this code path at all.

use specgate_fixtures::statemachine_counter;
use specgate_fixtures::stateless_add;
use specgate_fixtures::multi_field_capture;
use specgate_fixtures::checkpoint_inline;

// The annotations system must provide a way to retrieve collected traces.
// This import path may be specgate_annotations::take_traces, a runtime crate,
// or any other public API — as long as it drains the trace buffer.
use specgate_annotations::take_traces;

#[test]
fn stateless_operation_emits_traces() {
    let result = stateless_add::add(2, 3);
    assert_eq!(result, 5);

    let traces = take_traces();
    assert!(!traces.is_empty(), "annotations must emit real trace events");
}

#[test]
fn statemachine_operation_emits_field_events() {
    let mut counter = statemachine_counter::make_counter();
    counter.increment();

    let traces = take_traces();
    assert!(!traces.is_empty(), "annotations must emit real trace events");

    // Must contain field captures for 'count'.
    let trace_names: Vec<_> = traces.iter().map(|t| t.name()).collect();
    assert!(
        trace_names.iter().any(|n| n == "count"),
        "must capture the 'count' field via SpecEvent derive, got: {:?}",
        trace_names
    );
}

#[test]
fn multi_field_captures_all_annotated_fields() {
    let mut account = multi_field_capture::make_account();
    account.withdraw(30);

    let traces = take_traces();
    assert!(!traces.is_empty());

    let trace_names: Vec<_> = traces.iter().map(|t| t.name()).collect();
    assert!(
        trace_names.iter().any(|n| n == "balance"),
        "must capture 'balance' field, got: {:?}",
        trace_names
    );
    assert!(
        trace_names.iter().any(|n| n == "transaction_count"),
        "must capture 'transaction_count' field, got: {:?}",
        trace_names
    );
}

#[test]
fn inline_checkpoint_emits_event() {
    let result = checkpoint_inline::process("  hello  ");
    assert_eq!(result, "HELLO");

    let traces = take_traces();
    assert!(!traces.is_empty());

    let trace_names: Vec<_> = traces.iter().map(|t| t.name()).collect();
    assert!(
        trace_names.iter().any(|n| n == "after_upper"),
        "spec_event_record! must emit a named event, got: {:?}",
        trace_names
    );
}
