//! Self-emission regression test.
//!
//! DO NOT EDIT THIS FILE. This is a hand-written constraint verifying that an
//! annotated `#[spec_operation]` free function emits its FULL trace — including
//! the `$result` event — entirely on its own, without the harness runner
//! injecting anything. Record-mode case capture relies on this: it observes
//! the events a plain `#[test]` produces when it calls the op directly.
//!
//! If this test fails, the `#[spec_operation]` macro's self-emission was
//! broken — fix the macro/runtime, not this file.

use specgate::{TraceEvent, Value, reset, take_traces};
use specgate_fixtures::conformance::basic::stateless_add;

#[test]
fn free_function_self_emits_full_trace_including_result() {
    reset();

    let result = stateless_add::add(2, 3);
    assert_eq!(result, 5);

    let traces = take_traces();

    let expected = vec![
        TraceEvent::Run {
            operation: "add".to_string(),
        },
        TraceEvent::Event {
            name: "add.a".to_string(),
            value: Value::Integer(2),
        },
        TraceEvent::Event {
            name: "add.b".to_string(),
            value: Value::Integer(3),
        },
        TraceEvent::Event {
            name: "$result".to_string(),
            value: Value::Integer(5),
        },
    ];

    assert_eq!(
        traces, expected,
        "a direct call to an annotated free function must self-emit \
         $run, the input echoes, and $result — got: {traces:?}",
    );
}
